name: generate contributions graph animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # for manual runs
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v2
      
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            img/snake/github-contribution-grid-snake.svg?color_snake=#DE3163
            img/snake/github-contribution-grid-snake-dark.svg?palette=github-dark&?color_snake=#DE3163
      
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # push to the output branch
          target_branch: output
          build_dir: img/snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
